modules:ecs:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\necs\\n"

modules:editor:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\neditor\\n"

modules:graphics-2d:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\ngraphics-2d\\n"

modules:input:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\ninput\\n"

modules:music:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\nmusic\\n"

modules:network:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\nnetwork\\n"

modules:sound:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\nsound\\n"

packages:asset:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\nasset\\n"

packages:common:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\ncommon\\n"

packages:core:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\ncore\\n"

packages:env:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\nenv\\n"

utils:eslint-config:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\neslint-config\\n"

utils:prettier-config:
  - "### Which (package|utils|package or utils) is this (bug
    report|feature request) for\\?\\n\\nprettier-config\\n"
