documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/*
          - docs/**/*
          - modules/ecs/docs/*
          - modules/ecs/docs/**/*

modules:ecs:
  - changed-files:
      - any-glob-to-any-file:
          - modules/ecs/*
          - modules/ecs/**/*

modules:editor:
  - changed-files:
      - any-glob-to-any-file:
          - modules/editor/*
          - modules/editor/**/*

modules:graphics-2d:
  - changed-files:
      - any-glob-to-any-file:
          - modules/graphics-2d/*
          - modules/graphics-2d/**/*

modules:input:
  - changed-files:
      - any-glob-to-any-file:
          - modules/input/*
          - modules/input/**/*

modules:music:
  - changed-files:
      - any-glob-to-any-file:
          - modules/music/*
          - modules/music/**/*

modules:network:
  - changed-files:
      - any-glob-to-any-file:
          - modules/network/*
          - modules/network/**/*

modules:sound:
  - changed-files:
      - any-glob-to-any-file:
          - modules/sound/*
          - modules/sound/**/*

packages:asset:
  - changed-files:
      - any-glob-to-any-file:
          - packages/asset/*
          - packages/asset/**/*

packages:common:
  - changed-files:
      - any-glob-to-any-file:
          - packages/common/*
          - packages/common/**/*

packages:core:
  - changed-files:
      - any-glob-to-any-file:
          - packages/core/*
          - packages/core/**/*

packages:env:
  - changed-files:
      - any-glob-to-any-file:
          - packages/env/*
          - packages/env/**/*

utils:eslint-config:
  - changed-files:
      - any-glob-to-any-file:
          - utils/eslint-config/*
          - utils/eslint-config/**/*

utils:prettier-config:
  - changed-files:
      - any-glob-to-any-file:
          - utils/prettier-config/*
          - utils/prettier-config/**/*
