name: prepare
description: Prepare action
inputs:
  pnpm-install:
    description: Install pnpm depedencies
    default: "true"
  emsdk-install:
    description: Install emscriptens
    default: "true"
  build:
    description: Build packages
    default: "true"
runs:
  using: composite
  steps:
    - if: inputs.pnpm-install == 'true'
      name: Install pnpm and Node.js
      uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c
      with:
        runtime: node@26
        cache: true

    - if: inputs.emsdk-install == 'true'
      name: Install emsdk
      uses: ./.github/actions/emsdk-install

    - if: inputs.build == 'true'
      name: Build packages
      shell: bash
      run: pnpm run build
