name: Pre-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version for the packages
        type: string
        required: true
      dry_run:
        description: Perform a dry run?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    name: Create release pr
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Create release PR
        uses: ./node_modules/@nanoforge-dev/actions/actions/create-packages-release-pr
        with:
          packages: "@nanoforge-dev/asset-manager,@nanoforge-dev/common,@nanoforge-dev/config,@nanoforge-dev/core,@nanoforge-dev/core-editor,@nanoforge-dev/ecs-client,@nanoforge-dev/ecs-lib,@nanoforge-dev/ecs-server,@nanoforge-dev/graphics-2d,@nanoforge-dev/graphics-2d-editor,@nanoforge-dev/input,@nanoforge-dev/music,@nanoforge-dev/network-client,@nanoforge-dev/network-server,@nanoforge-dev/sound"
          version: ${{ inputs.version }}
          branch-format: "releases/nanoforge@{version}"
          commit-format: "chore: release @nanoforge-dev/engine@{version}"
          dry: ${{ inputs.dry_run }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
