name: Synchronize Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "packages/ecs-lib/docs/**"
      - "packages/ecs-lib/wasm/**"
  workflow_dispatch:

env:
  SOURCE_PATH: "engine"

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout engine
        uses: actions/checkout@v6
        with:
          path: ${{ env.SOURCE_PATH }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          package-manager-cache: false
          registry-url: https://registry.npmjs.org/

      - uses: ./engine/.github/actions/pnpm-install
        name: Install dependencies
        with:
          path: ${{ env.SOURCE_PATH }}

      - uses: ./engine/.github/actions/emsdk-install
        name: Install emsdk

      - name: prepare docs
        run: |
          pnpm run build
          pnpm run docs
        working-directory: ${{ env.SOURCE_PATH }}

      - name: synchronize docs
        uses: ./engine/node_modules/@nanoforge-dev/actions/src/synchronize-docs
        with:
          source-docs: ${{ env.SOURCE_PATH }}/docs
          destination-docs: docs/engine
          repository: nanoforge-dev/docs
          config: ${{ env.SOURCE_PATH }}/docs.json
          token: ${{ secrets.ACTIONS_KEY }}
          commit-message: "Update engine documentation"
