name: Synchronize Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "packages/ecs-lib/docs/**"
      - "packages/ecs-lib/wasm/**"
  workflow_dispatch:

env:
  SOURCE_PATH: "engine"

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout engine
        uses: actions/checkout@v6
        with:
          path: ${{ env.SOURCE_PATH }}

      - name: Checkout docs
        uses: actions/checkout@v6
        with:
          path: docs-repo
          repository: nanoforge-dev/docs
          token: ${{ secrets.ACTIONS_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          package-manager-cache: false
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v6.0.8
        name: Install pnpm
        with:
          run_install: false

      - name: setup git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "username@users.noreply.github.com"

      - name: install deps
        run: pnpm i
        working-directory: ${{ env.SOURCE_PATH }}

      - name: prepare docs
        run: |
          pnpm run docs
        working-directory: ${{ env.SOURCE_PATH }}

      - name: synchronize docs
        uses: ./schematics/node_modules/@nanoforge-dev/actions/src/synchronize-docs
        with:
          source-docs: ${{ env.SOURCE_PATH }}/docs
          destination-docs: docs/engine
          repository: nanoforge-dev/docs
          config: ${{ env.SOURCE_PATH }}/docs.json
          token: ${{ secrets.ACTIONS_KEY }}
          commit-message: "Update engine documentation"
