name: release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-pre"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building stack

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build ${{ matrix.projects }}
        run: |
          pnpm run build
          
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
