name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  EM_CACHE_FOLDER: "emsdk-cache"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
  setup:
    needs: checkout
    uses: './.github/workflows/setup.yml'

  tests:
    runs-on: ubuntu-latest
    needs: [checkout, setup]
    steps:
      - name: "Run build"
        run: pnpm build

      - name: "Run tests"
        run: pnpm test:unit

      - name: "Run linter"
        run: pnpm clean && pnpm lint
